name: Generate Snake
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: nischalg8
          outputs: dist/github-contribution-grid-snake-dark.svg

      - name: Commit and push to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch origin output || git checkout --orphan output
          git checkout output || git checkout --orphan output


          mkdir -p dist


          git add dist/github-contribution-grid-snake-dark.svg

          git commit -m "Update contribution snake" || echo "No changes to commit"


          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
